--------------------------------------------------------
--  文件已创建 - 星期日-六月-09-2019   
--------------------------------------------------------
DROP TYPE "SPIDER_MEN"."BLOGCOMMENT_TABLE";
DROP TYPE "SPIDER_MEN"."BLOG_TABLE";
DROP TYPE "SPIDER_MEN"."COURSE_TABLE";
DROP TYPE "SPIDER_MEN"."T_BLOGCOMMENT_TABLE";
DROP TYPE "SPIDER_MEN"."T_BLOG_TABLE";
DROP TYPE "SPIDER_MEN"."T_COURSE_TABLE";
DROP TABLE "SPIDER_MEN"."ASS_ADMIN" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_ATTITUDE_BLOG" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_BLOG" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_BLOG_LABEL" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_COLLECT_BLOG" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_COMMENT_BLOG" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_COURSE" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_COURSE_EXP" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_COURSE_TESTPAPER" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_COURSE_UPLOADEXP" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_MAJOR" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_REPORT_BLOG" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_SELECT_COURSE" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_STUDENT" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_TEACHER" cascade constraints;
DROP TABLE "SPIDER_MEN"."ASS_USER" cascade constraints;
DROP SEQUENCE "SPIDER_MEN"."ASS_ATTITUDE_BLOG_SEQ";
DROP SEQUENCE "SPIDER_MEN"."ASS_BLOG_LABEL_SEQ";
DROP SEQUENCE "SPIDER_MEN"."ASS_BLOG_SEQ";
DROP SEQUENCE "SPIDER_MEN"."ASS_COLLECT_BLOG_SEQ";
DROP SEQUENCE "SPIDER_MEN"."ASS_COMMENT_BLOG_SEQ";
DROP SEQUENCE "SPIDER_MEN"."ASS_COURSE_EXP_SEQ";
DROP SEQUENCE "SPIDER_MEN"."ASS_COURSE_TESTPAPER_SEQ";
DROP SEQUENCE "SPIDER_MEN"."ASS_COURSE_UPLOADEXP_SEQ";
DROP SEQUENCE "SPIDER_MEN"."ASS_REPORT_BLOG_SEQ";
DROP SEQUENCE "SPIDER_MEN"."ASS_SELECT_COURSE_SEQ";
DROP PROCEDURE "SPIDER_MEN"."PRO_DELETE_BLOG_USERID";
DROP PROCEDURE "SPIDER_MEN"."PRO_SELECTBLOGBYID";
DROP PROCEDURE "SPIDER_MEN"."PRO_USER_ANNOUNCE_BLOG";
DROP PACKAGE "SPIDER_MEN"."PACK_DELETE";
DROP PACKAGE "SPIDER_MEN"."PACK_SELECT";
DROP PACKAGE "SPIDER_MEN"."PACK_USER_DELETE";
DROP PACKAGE "SPIDER_MEN"."PACK_USER_RESIGER";
DROP PACKAGE BODY "SPIDER_MEN"."PACK_DELETE";
DROP PACKAGE BODY "SPIDER_MEN"."PACK_SELECT";
DROP PACKAGE BODY "SPIDER_MEN"."PACK_USER_DELETE";
DROP PACKAGE BODY "SPIDER_MEN"."PACK_USER_RESIGER";
-- 无法呈现对象 SPIDER_MEN 的 TYPE DDL。带有 DBMS_METADATA 的 BLOGCOMMENT_TABLE 正在尝试内部生成器。
CREATE TYPE BLOGCOMMENT_TABLE AS OBJECT(
	PK_ID int,
	BLOG_ID	int,
	USER_ID	char(10),
    NICKNAME VARCHAR2(30),
	COMMENTS	varchar2(150),
	TIMES	varchar2(256)
);
-- 无法呈现对象 SPIDER_MEN 的 TYPE DDL。带有 DBMS_METADATA 的 BLOG_TABLE 正在尝试内部生成器。
CREATE TYPE BLOG_TABLE AS OBJECT(
	PK_ID int,
	BLOG_TITLE	varchar2(90),
	USER_ID	char(10),
	BLOG_CONTENT	varchar2(256),
	FILE_DOWNLOAD	varchar2(256),
	LAUNCH_TIME	varchar2(50),
	AUTHORITY	smallint,
	NICKNAME varchar2(30),
    COURSE_ID char(10)
);
-- 无法呈现对象 SPIDER_MEN 的 TYPE DDL。带有 DBMS_METADATA 的 COURSE_TABLE 正在尝试内部生成器。
CREATE TYPE COURSE_TABLE AS OBJECT(
	COURSE_ID	char(10),
	COURSE_NAME	varchar2(60),
	TEACHER_ID	char(10),
	MAJOR_ID	char(5),
	COURSE_PIC	varchar2(256),
	COURSE_OUTLINE_DOWNLOAD	varchar2(256),
	HAS_AGREDD	smallint,
	COURSE_INFO varchar2(2000)
);
-- 无法呈现对象 SPIDER_MEN 的 TYPE DDL。带有 DBMS_METADATA 的 T_BLOGCOMMENT_TABLE 正在尝试内部生成器。
CREATE TYPE T_BLOGCOMMENT_TABLE IS TABLE OF BLOGCOMMENT_TABLE;
-- 无法呈现对象 SPIDER_MEN 的 TYPE DDL。带有 DBMS_METADATA 的 T_BLOG_TABLE 正在尝试内部生成器。
CREATE TYPE T_BLOG_TABLE IS TABLE OF BLOG_TABLE;
-- 无法呈现对象 SPIDER_MEN 的 TYPE DDL。带有 DBMS_METADATA 的 T_COURSE_TABLE 正在尝试内部生成器。
CREATE TYPE T_COURSE_TABLE AS TABLE OF COURSE_TABLE;
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_ADMIN 正在尝试内部生成器。
CREATE TABLE ASS_ADMIN 
(
  PK_ID CHAR(10 BYTE) NOT NULL 
, NAME VARCHAR2(30 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_ADMIN
ADD CONSTRAINT SYS_C007679 PRIMARY KEY 
(
  PK_ID 
)
USING INDEX SYS_C007679
ENABLECREATE UNIQUE INDEX SYS_C007679 ON ASS_ADMIN (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ASS_ADMIN
ADD CONSTRAINT FK_ADM_USER_ID FOREIGN KEY
(
  PK_ID 
)
REFERENCES ASS_USER
(
  PK_ID 
)
ENABLE
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_ATTITUDE_BLOG 正在尝试内部生成器。
CREATE TABLE ASS_ATTITUDE_BLOG 
(
  PK_ID NUMBER(*, 0) NOT NULL 
, USER_ID CHAR(10 BYTE) NOT NULL 
, BLOG_ID NUMBER(*, 0) NOT NULL 
, ATTITUDE NUMBER(*, 0) NOT NULL 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_ATTITUDE_BLOG
ADD CONSTRAINT SYS_C007753 PRIMARY KEY 
(
  PK_ID 
)
USING INDEX SYS_C007753
ENABLECREATE UNIQUE INDEX SYS_C007753 ON ASS_ATTITUDE_BLOG (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ASS_ATTITUDE_BLOG
ADD CONSTRAINT FK_ATTITUDEBLOG_BLOG_ID FOREIGN KEY
(
  BLOG_ID 
)
REFERENCES ASS_BLOG
(
  PK_ID 
)
ENABLE
ALTER TABLE ASS_ATTITUDE_BLOG
ADD CONSTRAINT FK_ATTITUDEBLOG_USER_ID FOREIGN KEY
(
  USER_ID 
)
REFERENCES ASS_USER
(
  PK_ID 
)
ENABLE
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_BLOG 正在尝试内部生成器。
CREATE TABLE ASS_BLOG 
(
  PK_ID NUMBER(*, 0) NOT NULL 
, BLOG_TITLE VARCHAR2(90 BYTE) NOT NULL 
, BLOG_CONTENT VARCHAR2(256 BYTE) NOT NULL 
, FILE_DOWNLOAD VARCHAR2(256 BYTE) 
, LAUNCH_TIME DATE NOT NULL 
, AUTHORITY NUMBER(*, 0) NOT NULL 
, USER_ID CHAR(10 BYTE) NOT NULL 
, COURSE_ID CHAR(10 BYTE) 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_BLOG
ADD CONSTRAINT SYS_C007722 PRIMARY KEY 
(
  PK_ID 
)
USING INDEX SYS_C007722
ENABLECREATE UNIQUE INDEX SYS_C007722 ON ASS_BLOG (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ASS_BLOG
ADD CONSTRAINT FK_BLOG_COURSE_ID FOREIGN KEY
(
  COURSE_ID 
)
REFERENCES ASS_COURSE
(
  COURSE_ID 
)
ENABLE
ALTER TABLE ASS_BLOG
ADD CONSTRAINT FK_BLOG_USER_ID FOREIGN KEY
(
  USER_ID 
)
REFERENCES ASS_USER
(
  PK_ID 
)
ENABLE
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_BLOG_LABEL 正在尝试内部生成器。
CREATE TABLE ASS_BLOG_LABEL 
(
  PK_ID NUMBER(*, 0) NOT NULL 
, BLOG_ID NUMBER(*, 0) NOT NULL 
, LABEL NUMBER(*, 0) NOT NULL 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_BLOG_LABEL
ADD CONSTRAINT SYS_C007726 PRIMARY KEY 
(
  PK_ID 
)
USING INDEX SYS_C007726
ENABLECREATE UNIQUE INDEX SYS_C007726 ON ASS_BLOG_LABEL (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ASS_BLOG_LABEL
ADD CONSTRAINT FK_BLOG_ID FOREIGN KEY
(
  BLOG_ID 
)
REFERENCES ASS_BLOG
(
  PK_ID 
)
ENABLE
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_COLLECT_BLOG 正在尝试内部生成器。
CREATE TABLE ASS_COLLECT_BLOG 
(
  PK_ID NUMBER(*, 0) NOT NULL 
, USER_ID CHAR(10 BYTE) NOT NULL 
, BLOG_ID NUMBER(*, 0) NOT NULL 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_COLLECT_BLOG
ADD CONSTRAINT SYS_C007737 PRIMARY KEY 
(
  PK_ID 
)
USING INDEX SYS_C007737
ENABLECREATE UNIQUE INDEX SYS_C007737 ON ASS_COLLECT_BLOG (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ASS_COLLECT_BLOG
ADD CONSTRAINT FK_COLLECTBLOG_BLOG_ID FOREIGN KEY
(
  BLOG_ID 
)
REFERENCES ASS_BLOG
(
  PK_ID 
)
ENABLE
ALTER TABLE ASS_COLLECT_BLOG
ADD CONSTRAINT FK_COLLECTBLOG_USER_ID FOREIGN KEY
(
  USER_ID 
)
REFERENCES ASS_USER
(
  PK_ID 
)
ENABLE
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_COMMENT_BLOG 正在尝试内部生成器。
CREATE TABLE ASS_COMMENT_BLOG 
(
  PK_ID NUMBER(*, 0) NOT NULL 
, USER_ID CHAR(10 BYTE) NOT NULL 
, BLOG_ID NUMBER(*, 0) NOT NULL 
, COMMENTS VARCHAR2(150 BYTE) NOT NULL 
, TIMES DATE NOT NULL 
) 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL 
PARTITION BY RANGE (TIMES) 
(
  PARTITION P1 VALUES LESS THAN (TO_DATE(' 2019-06-01 10:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  LOGGING 
  TABLESPACE ACADEMIC_RESOURCE 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 8388608 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION P2 VALUES LESS THAN (TO_DATE(' 2020-06-01 10:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  LOGGING 
  TABLESPACE ACADEMIC_RESOURCE 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 8388608 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION P3 VALUES LESS THAN (TO_DATE(' 2021-06-01 10:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  LOGGING 
  TABLESPACE ACADEMIC_RESOURCE 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION P4 VALUES LESS THAN (TO_DATE(' 2022-06-01 10:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  LOGGING 
  TABLESPACE ACADEMIC_RESOURCE 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
, PARTITION P5 VALUES LESS THAN (TO_DATE(' 2023-06-01 10:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  LOGGING 
  TABLESPACE ACADEMIC_RESOURCE 
  PCTFREE 10 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  NOCOMPRESS  
)ALTER TABLE ASS_COMMENT_BLOG
ADD CONSTRAINT SYS_C009082 PRIMARY KEY 
(
  PK_ID 
)
USING INDEX SYS_C009082
ENABLECREATE UNIQUE INDEX SYS_C009082 ON ASS_COMMENT_BLOG (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ASS_COMMENT_BLOG
ADD CONSTRAINT FK_COMMENTBLOG_BLOG_ID_NEW FOREIGN KEY
(
  BLOG_ID 
)
REFERENCES ASS_BLOG
(
  PK_ID 
)
ENABLE
ALTER TABLE ASS_COMMENT_BLOG
ADD CONSTRAINT FK_COMMENTBLOG_USER_ID_NEW FOREIGN KEY
(
  USER_ID 
)
REFERENCES ASS_USER
(
  PK_ID 
)
ENABLE
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_COURSE 正在尝试内部生成器。
CREATE TABLE ASS_COURSE 
(
  COURSE_ID CHAR(10 BYTE) NOT NULL 
, COURSE_NAME VARCHAR2(60 BYTE) NOT NULL 
, TEACHER_ID CHAR(10 BYTE) NOT NULL 
, MAJOR_ID CHAR(5 BYTE) NOT NULL 
, COURSE_PIC VARCHAR2(256 BYTE) NOT NULL 
, COURSE_OUTLINE_DOWNLOAD VARCHAR2(256 BYTE) NOT NULL 
, HAS_AGREDD NUMBER(*, 0) NOT NULL 
, COURSE_INFO VARCHAR2(2000 BYTE) 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_COURSE
ADD CONSTRAINT SYS_C007688 PRIMARY KEY 
(
  COURSE_ID 
)
USING INDEX SYS_C007688
ENABLECREATE INDEX INDEX_COURSE_MAJORID ON ASS_COURSE (MAJOR_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE INDEX INDEX_COURSE_TEACHERID ON ASS_COURSE (TEACHER_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE UNIQUE INDEX SYS_C007688 ON ASS_COURSE (COURSE_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ASS_COURSE
ADD CONSTRAINT FK_COURSE_MAJOR_ID FOREIGN KEY
(
  MAJOR_ID 
)
REFERENCES ASS_MAJOR
(
  MAJOR_ID 
)
ENABLE
ALTER TABLE ASS_COURSE
ADD CONSTRAINT FK_COURSE_TEACHER_ID FOREIGN KEY
(
  TEACHER_ID 
)
REFERENCES ASS_TEACHER
(
  PK_ID 
)
ENABLE
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_COURSE_EXP 正在尝试内部生成器。
CREATE TABLE ASS_COURSE_EXP 
(
  PK_ID NUMBER(*, 0) NOT NULL 
, COURSE_ID CHAR(10 BYTE) NOT NULL 
, EXP_NAME VARCHAR2(60 BYTE) NOT NULL 
, DOWNLOAD VARCHAR2(256 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_COURSE_EXP
ADD CONSTRAINT SYS_C007707 PRIMARY KEY 
(
  PK_ID 
)
USING INDEX SYS_C007707
ENABLECREATE UNIQUE INDEX SYS_C007707 ON ASS_COURSE_EXP (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ASS_COURSE_EXP
ADD CONSTRAINT FK_COURSE_EXP_COURSE_ID FOREIGN KEY
(
  COURSE_ID 
)
REFERENCES ASS_COURSE
(
  COURSE_ID 
)
ENABLE
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_COURSE_TESTPAPER 正在尝试内部生成器。
CREATE TABLE ASS_COURSE_TESTPAPER 
(
  PK_ID NUMBER(*, 0) NOT NULL 
, COURSE_ID CHAR(10 BYTE) NOT NULL 
, PAPER_NAME VARCHAR2(60 BYTE) NOT NULL 
, DOWNLOAD VARCHAR2(256 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_COURSE_TESTPAPER
ADD CONSTRAINT SYS_C007701 PRIMARY KEY 
(
  PK_ID 
)
USING INDEX SYS_C007701
ENABLECREATE UNIQUE INDEX SYS_C007701 ON ASS_COURSE_TESTPAPER (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ASS_COURSE_TESTPAPER
ADD CONSTRAINT FK_COURSE_TESTPAPER FOREIGN KEY
(
  COURSE_ID 
)
REFERENCES ASS_COURSE
(
  COURSE_ID 
)
ENABLE
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_COURSE_UPLOADEXP 正在尝试内部生成器。
CREATE TABLE ASS_COURSE_UPLOADEXP 
(
  PK_ID NUMBER(*, 0) NOT NULL 
, STU_ID CHAR(10 BYTE) NOT NULL 
, EXP_ID NUMBER(*, 0) NOT NULL 
, SCORE NUMBER(*, 0) NOT NULL 
, UPLOAD VARCHAR2(256 BYTE) NOT NULL 
, UPLOAD_TIME DATE NOT NULL 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_COURSE_UPLOADEXP
ADD CONSTRAINT SYS_C007770 PRIMARY KEY 
(
  PK_ID 
)
USING INDEX SYS_C007770
ENABLECREATE UNIQUE INDEX SYS_C007770 ON ASS_COURSE_UPLOADEXP (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ASS_COURSE_UPLOADEXP
ADD CONSTRAINT FK_COURSEUPLOADEXP_COURSE_ID FOREIGN KEY
(
  EXP_ID 
)
REFERENCES ASS_COURSE_EXP
(
  PK_ID 
)
ENABLE
ALTER TABLE ASS_COURSE_UPLOADEXP
ADD CONSTRAINT FK_COURSEUPLOADEXP_SELECTCOURSE_ID FOREIGN KEY
(
  STU_ID 
)
REFERENCES ASS_STUDENT
(
  PK_ID 
)
ENABLE
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_MAJOR 正在尝试内部生成器。
CREATE TABLE ASS_MAJOR 
(
  MAJOR_ID CHAR(5 BYTE) NOT NULL 
, MAJOR_NAME VARCHAR2(60 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_MAJOR
ADD CONSTRAINT SYS_C007666 PRIMARY KEY 
(
  MAJOR_ID 
)
USING INDEX SYS_C007666
ENABLECREATE UNIQUE INDEX SYS_C007666 ON ASS_MAJOR (MAJOR_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_REPORT_BLOG 正在尝试内部生成器。
CREATE TABLE ASS_REPORT_BLOG 
(
  PK_ID NUMBER(*, 0) NOT NULL 
, USER_ID CHAR(10 BYTE) NOT NULL 
, BLOG_ID NUMBER(*, 0) NOT NULL 
, REASON NUMBER(*, 0) NOT NULL 
, TIME DATE NOT NULL 
, OPERATE_STATUS NUMBER(*, 0) NOT NULL 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_REPORT_BLOG
ADD CONSTRAINT SYS_C007746 PRIMARY KEY 
(
  PK_ID 
)
USING INDEX SYS_C007746
ENABLECREATE UNIQUE INDEX SYS_C007746 ON ASS_REPORT_BLOG (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ASS_REPORT_BLOG
ADD CONSTRAINT FK_REPORTBLOG_BLOG_ID FOREIGN KEY
(
  BLOG_ID 
)
REFERENCES ASS_BLOG
(
  PK_ID 
)
ENABLE
ALTER TABLE ASS_REPORT_BLOG
ADD CONSTRAINT FK_REPORTBLOG_USER_ID FOREIGN KEY
(
  USER_ID 
)
REFERENCES ASS_USER
(
  PK_ID 
)
ENABLE
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_SELECT_COURSE 正在尝试内部生成器。
CREATE TABLE ASS_SELECT_COURSE 
(
  PK_ID NUMBER(*, 0) NOT NULL 
, STU_ID CHAR(10 BYTE) NOT NULL 
, COURSE_ID CHAR(10 BYTE) NOT NULL 
, SCORE NUMBER(*, 0) 
, SCHEDULE VARCHAR2(2000 BYTE) 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_SELECT_COURSE
ADD CONSTRAINT SYS_C007694 PRIMARY KEY 
(
  PK_ID 
)
USING INDEX SYS_C007694
ENABLECREATE UNIQUE INDEX INDEX_SELECTCOURSE ON ASS_SELECT_COURSE (STU_ID ASC, COURSE_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE UNIQUE INDEX SYS_C007694 ON ASS_SELECT_COURSE (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ASS_SELECT_COURSE
ADD CONSTRAINT FK_SELECTCOURSE_COURSE_ID FOREIGN KEY
(
  COURSE_ID 
)
REFERENCES ASS_COURSE
(
  COURSE_ID 
)
ENABLE
ALTER TABLE ASS_SELECT_COURSE
ADD CONSTRAINT FK_SELECTCOURSE_STU_ID FOREIGN KEY
(
  STU_ID 
)
REFERENCES ASS_STUDENT
(
  PK_ID 
)
ENABLE
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_STUDENT 正在尝试内部生成器。
CREATE TABLE ASS_STUDENT 
(
  PK_ID CHAR(10 BYTE) NOT NULL 
, NAME VARCHAR2(30 BYTE) NOT NULL 
, MAJOR_ID CHAR(5 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_STUDENT
ADD CONSTRAINT SYS_C007670 PRIMARY KEY 
(
  PK_ID 
)
USING INDEX SYS_C007670
ENABLECREATE UNIQUE INDEX SYS_C007670 ON ASS_STUDENT (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ASS_STUDENT
ADD CONSTRAINT FK_STU_MAJOR_ID FOREIGN KEY
(
  MAJOR_ID 
)
REFERENCES ASS_MAJOR
(
  MAJOR_ID 
)
ENABLE
ALTER TABLE ASS_STUDENT
ADD CONSTRAINT FK_STU_USER_ID FOREIGN KEY
(
  PK_ID 
)
REFERENCES ASS_USER
(
  PK_ID 
)
ENABLE
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_TEACHER 正在尝试内部生成器。
CREATE TABLE ASS_TEACHER 
(
  PK_ID CHAR(10 BYTE) NOT NULL 
, NAME VARCHAR2(30 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_TEACHER
ADD CONSTRAINT SYS_C007675 PRIMARY KEY 
(
  PK_ID 
)
USING INDEX SYS_C007675
ENABLECREATE UNIQUE INDEX SYS_C007675 ON ASS_TEACHER (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ASS_TEACHER
ADD CONSTRAINT FK_TEA_USER_ID FOREIGN KEY
(
  PK_ID 
)
REFERENCES ASS_USER
(
  PK_ID 
)
ENABLE
-- 无法呈现对象 SPIDER_MEN 的 TABLE DDL。带有 DBMS_METADATA 的 ASS_USER 正在尝试内部生成器。
CREATE TABLE ASS_USER 
(
  PK_ID CHAR(10 BYTE) NOT NULL 
, PASSWORD VARCHAR2(100 BYTE) NOT NULL 
, ROLE NUMBER(*, 0) NOT NULL 
, NICKNAME VARCHAR2(30 BYTE) 
) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE ASS_USER
ADD CONSTRAINT SYS_C007663 PRIMARY KEY 
(
  PK_ID 
)
USING INDEX SYS_C007663
ENABLECREATE UNIQUE INDEX SYS_C007663 ON ASS_USER (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 SEQUENCE DDL。带有 DBMS_METADATA 的 ASS_ATTITUDE_BLOG_SEQ 正在尝试内部生成器。
CREATE SEQUENCE ASS_ATTITUDE_BLOG_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999 MINVALUE 1 CACHE 20
-- 无法呈现对象 SPIDER_MEN 的 SEQUENCE DDL。带有 DBMS_METADATA 的 ASS_BLOG_LABEL_SEQ 正在尝试内部生成器。
CREATE SEQUENCE ASS_BLOG_LABEL_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999 MINVALUE 1 CACHE 20
-- 无法呈现对象 SPIDER_MEN 的 SEQUENCE DDL。带有 DBMS_METADATA 的 ASS_BLOG_SEQ 正在尝试内部生成器。
CREATE SEQUENCE ASS_BLOG_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999 MINVALUE 1 CACHE 20
-- 无法呈现对象 SPIDER_MEN 的 SEQUENCE DDL。带有 DBMS_METADATA 的 ASS_COLLECT_BLOG_SEQ 正在尝试内部生成器。
CREATE SEQUENCE ASS_COLLECT_BLOG_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999 MINVALUE 1 CACHE 20
-- 无法呈现对象 SPIDER_MEN 的 SEQUENCE DDL。带有 DBMS_METADATA 的 ASS_COMMENT_BLOG_SEQ 正在尝试内部生成器。
CREATE SEQUENCE ASS_COMMENT_BLOG_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999 MINVALUE 1 CACHE 20
-- 无法呈现对象 SPIDER_MEN 的 SEQUENCE DDL。带有 DBMS_METADATA 的 ASS_COURSE_EXP_SEQ 正在尝试内部生成器。
CREATE SEQUENCE ASS_COURSE_EXP_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999 MINVALUE 1 CACHE 20
-- 无法呈现对象 SPIDER_MEN 的 SEQUENCE DDL。带有 DBMS_METADATA 的 ASS_COURSE_TESTPAPER_SEQ 正在尝试内部生成器。
CREATE SEQUENCE ASS_COURSE_TESTPAPER_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999 MINVALUE 1 CACHE 20
-- 无法呈现对象 SPIDER_MEN 的 SEQUENCE DDL。带有 DBMS_METADATA 的 ASS_COURSE_UPLOADEXP_SEQ 正在尝试内部生成器。
CREATE SEQUENCE ASS_COURSE_UPLOADEXP_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999 MINVALUE 1 CACHE 20
-- 无法呈现对象 SPIDER_MEN 的 SEQUENCE DDL。带有 DBMS_METADATA 的 ASS_REPORT_BLOG_SEQ 正在尝试内部生成器。
CREATE SEQUENCE ASS_REPORT_BLOG_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999 MINVALUE 1 CACHE 20
-- 无法呈现对象 SPIDER_MEN 的 SEQUENCE DDL。带有 DBMS_METADATA 的 ASS_SELECT_COURSE_SEQ 正在尝试内部生成器。
CREATE SEQUENCE ASS_SELECT_COURSE_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999 MINVALUE 1 CACHE 20
REM INSERTING into SPIDER_MEN.ASS_ADMIN
SET DEFINE OFF;
Insert into SPIDER_MEN.ASS_ADMIN (PK_ID,NAME) values ('1105040001','倪虹灯');
Insert into SPIDER_MEN.ASS_ADMIN (PK_ID,NAME) values ('0104150015','许强');
REM INSERTING into SPIDER_MEN.ASS_ATTITUDE_BLOG
SET DEFINE OFF;
REM INSERTING into SPIDER_MEN.ASS_BLOG
SET DEFINE OFF;
Insert into SPIDER_MEN.ASS_BLOG (PK_ID,BLOG_TITLE,BLOG_CONTENT,FILE_DOWNLOAD,LAUNCH_TIME,AUTHORITY,USER_ID,COURSE_ID) values (142,'课程设计','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogContent/1609011903/16090119032019_06_08_22_30_38','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogAttachment/1609011903/16090119032019_06_08_22_30_38',to_date('08-6月 -19','DD-MON-RR'),2,'1609011903','9001049371');
Insert into SPIDER_MEN.ASS_BLOG (PK_ID,BLOG_TITLE,BLOG_CONTENT,FILE_DOWNLOAD,LAUNCH_TIME,AUTHORITY,USER_ID,COURSE_ID) values (162,'中国梦','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogContent/1709011301/17090113012019_06_09_15_42_01','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogAttachment/1709011301/17090113012019_06_09_15_42_01',to_date('09-6月 -19','DD-MON-RR'),2,'1709011301','9001049371');
Insert into SPIDER_MEN.ASS_BLOG (PK_ID,BLOG_TITLE,BLOG_CONTENT,FILE_DOWNLOAD,LAUNCH_TIME,AUTHORITY,USER_ID,COURSE_ID) values (81,'PHP专题','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogContent/16090100012019_05_24_10_03_29','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogAttachment/16090100012019_05_24_10_03_29',to_date('24-5月 -19','DD-MON-RR'),2,'1609010001',null);
Insert into SPIDER_MEN.ASS_BLOG (PK_ID,BLOG_TITLE,BLOG_CONTENT,FILE_DOWNLOAD,LAUNCH_TIME,AUTHORITY,USER_ID,COURSE_ID) values (82,'菜鸡互啄','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogContent/16090100012019_05_24_12_20_03','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogAttachment/16090100012019_05_24_12_20_03',to_date('24-5月 -19','DD-MON-RR'),2,'1609010001',null);
Insert into SPIDER_MEN.ASS_BLOG (PK_ID,BLOG_TITLE,BLOG_CONTENT,FILE_DOWNLOAD,LAUNCH_TIME,AUTHORITY,USER_ID,COURSE_ID) values (61,'J2EE的基础','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogContent/16090100012019_05_23_23_48_32','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogAttachment/16090100012019_05_23_23_48_32',to_date('23-5月 -19','DD-MON-RR'),2,'1609010001',null);
Insert into SPIDER_MEN.ASS_BLOG (PK_ID,BLOG_TITLE,BLOG_CONTENT,FILE_DOWNLOAD,LAUNCH_TIME,AUTHORITY,USER_ID,COURSE_ID) values (101,'断桥残雪','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogContent/16090100012019_05_26_16_07_25','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogAttachment/16090100012019_05_26_16_07_25',to_date('26-5月 -19','DD-MON-RR'),2,'1609010001',null);
Insert into SPIDER_MEN.ASS_BLOG (PK_ID,BLOG_TITLE,BLOG_CONTENT,FILE_DOWNLOAD,LAUNCH_TIME,AUTHORITY,USER_ID,COURSE_ID) values (103,'断桥残雪','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogContent/1609010001/16090100012019_05_26_16_16_44','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogAttachment/1609010001/16090100012019_05_26_16_16_44',to_date('26-5月 -19','DD-MON-RR'),2,'1609010001',null);
Insert into SPIDER_MEN.ASS_BLOG (PK_ID,BLOG_TITLE,BLOG_CONTENT,FILE_DOWNLOAD,LAUNCH_TIME,AUTHORITY,USER_ID,COURSE_ID) values (121,'武王的功力','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogContent/1609011903/16090119032019_06_05_23_32_25','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogAttachment/1609011903/16090119032019_06_05_23_32_25',to_date('05-6月 -19','DD-MON-RR'),2,'1609011903',null);
Insert into SPIDER_MEN.ASS_BLOG (PK_ID,BLOG_TITLE,BLOG_CONTENT,FILE_DOWNLOAD,LAUNCH_TIME,AUTHORITY,USER_ID,COURSE_ID) values (141,'务必坚持一个中国','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogContent/1609011903/16090119032019_06_08_15_49_32','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/blogs/blogAttachment/1609011903/16090119032019_06_08_15_49_32',to_date('08-6月 -19','DD-MON-RR'),2,'1609011903','9001049371');
REM INSERTING into SPIDER_MEN.ASS_BLOG_LABEL
SET DEFINE OFF;
REM INSERTING into SPIDER_MEN.ASS_COLLECT_BLOG
SET DEFINE OFF;
REM INSERTING into SPIDER_MEN.ASS_COMMENT_BLOG
SET DEFINE OFF;
Insert into SPIDER_MEN.ASS_COMMENT_BLOG (PK_ID,USER_ID,BLOG_ID,COMMENTS,TIMES) values (1,'1609010001',82,'明天会更好',to_date('24-5月 -19','DD-MON-RR'));
Insert into SPIDER_MEN.ASS_COMMENT_BLOG (PK_ID,USER_ID,BLOG_ID,COMMENTS,TIMES) values (2,'1609010001',82,'明天不太好',to_date('24-5月 -19','DD-MON-RR'));
Insert into SPIDER_MEN.ASS_COMMENT_BLOG (PK_ID,USER_ID,BLOG_ID,COMMENTS,TIMES) values (3,'1609010001',82,'哈哈哈',to_date('04-6月 -19','DD-MON-RR'));
Insert into SPIDER_MEN.ASS_COMMENT_BLOG (PK_ID,USER_ID,BLOG_ID,COMMENTS,TIMES) values (21,'1609010001',121,'武王666',to_date('05-6月 -19','DD-MON-RR'));
Insert into SPIDER_MEN.ASS_COMMENT_BLOG (PK_ID,USER_ID,BLOG_ID,COMMENTS,TIMES) values (22,'1609011903',121,'武王6666',to_date('05-6月 -19','DD-MON-RR'));
Insert into SPIDER_MEN.ASS_COMMENT_BLOG (PK_ID,USER_ID,BLOG_ID,COMMENTS,TIMES) values (23,'1609011903',101,'1234',to_date('06-6月 -19','DD-MON-RR'));
REM INSERTING into SPIDER_MEN.ASS_COURSE
SET DEFINE OFF;
Insert into SPIDER_MEN.ASS_COURSE (COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO) values ('9001049371','黑洞鉴赏','0506010001','00000','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/pic/9001049371','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/outlines/9001049371',1,'无');
Insert into SPIDER_MEN.ASS_COURSE (COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO) values ('1000003854','大学英语','0506010001','00000','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/pic/DefaultCoursePic.jpg','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/outlines/CourseOutline%28Default%29.docx',1,'无');
Insert into SPIDER_MEN.ASS_COURSE (COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO) values ('3082040281','密码学','0907180491','10002','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/pic/DefaultCoursePic.jpg','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/outlines/CourseOutline%28Default%29.docx',3,'密码学（在西欧语文中，源于希腊语kryptós“隐藏的”，和gráphein“书写”）是研究如何隐密地传递信息的学科。在现代特别指对信息以及其传输的数学性研究，常被认为是数学和计算机科学的分支，和信息论也密切相关。著名的密码学者Ron Rivest解释道：“密码学是关于如何在敌人存在的环境中通讯”，自工程学的角度，这相当于密码学与纯数学的异同。密码学是信息安全等相关议题，如认证、访问控制的核心。密码学的首要目的是隐藏信息的涵义，并不是隐藏信息的存在。密码学也促进了计算机科学，特别是在于电脑与网络安全所使用的技术，如访问控制与信息的机密性。密码学已被应用在日常生活：包括自动柜员机的芯片卡、电脑使用者存取密码、电子商务等等。');
Insert into SPIDER_MEN.ASS_COURSE (COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO) values ('2083019403','网络攻防技术','0907180491','10002','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/pic/DefaultCoursePic.jpg','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/outlines/CourseOutline%28Default%29.docx',1,'从网络安全所面临的不同威胁入手，详细介绍了信息收集、口令攻击、缓冲区溢出、恶意代码、Web应用程序攻击、嗅探、假消息、拒绝服务攻击等多种攻击技术，并给出一定的实例分析。从网络安全、访问控制机制、防火墙技术、入侵检测、蜜罐技术等方面系统介绍网络安全防御技术，进而分析了内网安全管理的技术和手段。');
Insert into SPIDER_MEN.ASS_COURSE (COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO) values ('3019586000','计算机导论','0506010001','00000','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/pic/3019586000','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/outlines/3019586000',1,'无');
Insert into SPIDER_MEN.ASS_COURSE (COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO) values ('1000000000','面向对象分析与设计','0506010001','10000','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/pic/DefaultCoursePic.jpg','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/outlines/CourseOutline%28Default%29.docx',1,'从程序设计方法的角度看，面向对象是一种新的程序设计范型(paradigm)，其基本思想是使用对象、类、继承、封装、聚合、关联、消息、多态性等基本概念来进行程序设计。是一种运用对象、类、继承、封装、聚合、关联、消息、多态性等概念来构造系统的软件开发方法。');
Insert into SPIDER_MEN.ASS_COURSE (COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO) values ('1240381001','软件测试与质量控制','0506010001','10000','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/pic/DefaultCoursePic.jpg','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/outlines/CourseOutline%28Default%29.docx',1,'软件测试方法是指测试软件的方法。随着软件测试技术的不断发展，测试方法也越来越多样化，针对性更强；选择合适的软件测试方法可以让我们事半功倍。');
Insert into SPIDER_MEN.ASS_COURSE (COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO) values ('1038103901','大型网站设计架构与模式','0506010001','10000','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/pic/DefaultCoursePic.jpg','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/outlines/CourseOutline%28Default%29.docx',1,'软件架构是一个系统的草图。软件架构描述的对象是直接构成系统的抽象组件。各个组件之间的连接则明确和相对细致地描述组件之间的通讯。在实现阶段，这些抽象组件被细化为实际的组件，比如具体某个类或者对象。在面向对象领域中，组件之间的连接通常用接口来实现。');
Insert into SPIDER_MEN.ASS_COURSE (COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO) values ('4019294010','大数据Spark开发与流计算','0506010001','10000','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/pic/DefaultCoursePic.jpg','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/outlines/CourseOutline%28Default%29.docx',3,'Spark作为下一代大数据处理引擎，经过短短几年的飞跃式发展，正在以燎原之势席卷业界，现已成为大数据产业中的一股中坚力量。');
Insert into SPIDER_MEN.ASS_COURSE (COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO) values ('3082018451','信息安全概论','0907180491','10002','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/pic/DefaultCoursePic.jpg','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/outlines/CourseOutline%28Default%29.docx',2,'全面介绍信息安全的基本概念、原理和知识体系，主要内容包括信息保密技术、信息认证技术、密钥管理技术、访问控制技术、数据库安全、网络安全技术、信息安全标准和信息安全管理等内容。');
Insert into SPIDER_MEN.ASS_COURSE (COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO) values ('1010101010','通信工程概论','0506010001','20004','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/pic/1010101010','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/outlines/1010101010',1,'无');
Insert into SPIDER_MEN.ASS_COURSE (COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO) values ('1234554321','JAVAEE(双语)','0506010001','10000','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/pic/DefaultCoursePic.jpg','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/outlines/CourseOutline%28Default%29.docx',1,'Java EE，Java 平台企业版（Java Platform Enterprise Edition）。是 Sun 公司为企业级应用推出的标准平台，用来开发B/S架构软件。Java EE 可以说是一个框架，也可以说是一种规范。');
Insert into SPIDER_MEN.ASS_COURSE (COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO) values ('2019481033','软件工程概论','0506010001','10000','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/pic/DefaultCoursePic.jpg','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/outlines/CourseOutline%28Default%29.docx',3,'软件工程是一门研究用工程化方法构建和维护有效的、实用的和高质量的软件的学科。它涉及程序设计语言、数据库、软件开发工具、系统平台、标准、设计模式等方面。');
Insert into SPIDER_MEN.ASS_COURSE (COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO) values ('9000493010','文学导读 —— 我心中的王小波','0907180491','00000','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/pic/9000493010','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/outlines/9000493010',1,'无');
REM INSERTING into SPIDER_MEN.ASS_COURSE_EXP
SET DEFINE OFF;
Insert into SPIDER_MEN.ASS_COURSE_EXP (PK_ID,COURSE_ID,EXP_NAME,DOWNLOAD) values (1,'1240381001','实验一 等价类法和边界值法','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/exps/1240381001/2019-05-25_16-51-39');
Insert into SPIDER_MEN.ASS_COURSE_EXP (PK_ID,COURSE_ID,EXP_NAME,DOWNLOAD) values (2,'1000000000','实验一 用例图','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/exps/1000000000/2019-05-27_19-54-00');
Insert into SPIDER_MEN.ASS_COURSE_EXP (PK_ID,COURSE_ID,EXP_NAME,DOWNLOAD) values (3,'9000493010','读后感 王小波撰写的《黑铁时代》','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/exps/9000493010/2019-05-28_18-35-00');
Insert into SPIDER_MEN.ASS_COURSE_EXP (PK_ID,COURSE_ID,EXP_NAME,DOWNLOAD) values (4,'1038103901','实验二','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/exps/1038103901/2019-06-04_20-32-47');
Insert into SPIDER_MEN.ASS_COURSE_EXP (PK_ID,COURSE_ID,EXP_NAME,DOWNLOAD) values (5,'1038103901','实验一','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/exps/1038103901/2019-05-25_16-10-52');
Insert into SPIDER_MEN.ASS_COURSE_EXP (PK_ID,COURSE_ID,EXP_NAME,DOWNLOAD) values (6,'1234554321','实验一 可行性分析','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/exps/1234554321/2019-05-25_16-19-13');
Insert into SPIDER_MEN.ASS_COURSE_EXP (PK_ID,COURSE_ID,EXP_NAME,DOWNLOAD) values (13,'1240381001','实验二 集成测试','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/exps/1240381001/2019-06-05_23-18-50');
REM INSERTING into SPIDER_MEN.ASS_COURSE_TESTPAPER
SET DEFINE OFF;
Insert into SPIDER_MEN.ASS_COURSE_TESTPAPER (PK_ID,COURSE_ID,PAPER_NAME,DOWNLOAD) values (1,'1038103901','实验一 设计模式——静态工厂模式','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/testPapers/1038103901/2019-05-25_16-31-42');
Insert into SPIDER_MEN.ASS_COURSE_TESTPAPER (PK_ID,COURSE_ID,PAPER_NAME,DOWNLOAD) values (2,'1000000000','用例图与类图','https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/testPapers/1000000000/2019-05-25_16-15-08');
REM INSERTING into SPIDER_MEN.ASS_COURSE_UPLOADEXP
SET DEFINE OFF;
Insert into SPIDER_MEN.ASS_COURSE_UPLOADEXP (PK_ID,STU_ID,EXP_ID,SCORE,UPLOAD,UPLOAD_TIME) values (4,'1609011903',3,0,'https://academic-shared-system.oss-cn-shanghai.aliyuncs.com/courses/uploadExps/9000493010/1609011903_42',to_date('28-5月 -19','DD-MON-RR'));
REM INSERTING into SPIDER_MEN.ASS_MAJOR
SET DEFINE OFF;
Insert into SPIDER_MEN.ASS_MAJOR (MAJOR_ID,MAJOR_NAME) values ('20001','电子信息科学与技术');
Insert into SPIDER_MEN.ASS_MAJOR (MAJOR_ID,MAJOR_NAME) values ('20002','通讯工程');
Insert into SPIDER_MEN.ASS_MAJOR (MAJOR_ID,MAJOR_NAME) values ('20004','通信工程');
Insert into SPIDER_MEN.ASS_MAJOR (MAJOR_ID,MAJOR_NAME) values ('00000','高校基础课程');
Insert into SPIDER_MEN.ASS_MAJOR (MAJOR_ID,MAJOR_NAME) values ('10000','软件工程');
Insert into SPIDER_MEN.ASS_MAJOR (MAJOR_ID,MAJOR_NAME) values ('10001','计算机科学与技术');
Insert into SPIDER_MEN.ASS_MAJOR (MAJOR_ID,MAJOR_NAME) values ('10002','信息安全');
Insert into SPIDER_MEN.ASS_MAJOR (MAJOR_ID,MAJOR_NAME) values ('10003','网络安全');
REM INSERTING into SPIDER_MEN.ASS_REPORT_BLOG
SET DEFINE OFF;
Insert into SPIDER_MEN.ASS_REPORT_BLOG (PK_ID,USER_ID,BLOG_ID,REASON,TIME,OPERATE_STATUS) values (21,'1609010001',82,1,to_date('02-6月 -19','DD-MON-RR'),1);
REM INSERTING into SPIDER_MEN.ASS_SELECT_COURSE
SET DEFINE OFF;
Insert into SPIDER_MEN.ASS_SELECT_COURSE (PK_ID,STU_ID,COURSE_ID,SCORE,SCHEDULE) values (1,'1709011300','1000003854',null,null);
Insert into SPIDER_MEN.ASS_SELECT_COURSE (PK_ID,STU_ID,COURSE_ID,SCORE,SCHEDULE) values (2,'1709011300','3082040281',null,null);
Insert into SPIDER_MEN.ASS_SELECT_COURSE (PK_ID,STU_ID,COURSE_ID,SCORE,SCHEDULE) values (3,'1609011903','1234554321',null,null);
Insert into SPIDER_MEN.ASS_SELECT_COURSE (PK_ID,STU_ID,COURSE_ID,SCORE,SCHEDULE) values (4,'1609011903','2019481033',5,null);
Insert into SPIDER_MEN.ASS_SELECT_COURSE (PK_ID,STU_ID,COURSE_ID,SCORE,SCHEDULE) values (5,'1609011903','9000493010',null,null);
Insert into SPIDER_MEN.ASS_SELECT_COURSE (PK_ID,STU_ID,COURSE_ID,SCORE,SCHEDULE) values (6,'1609011903','4019294010',4,null);
Insert into SPIDER_MEN.ASS_SELECT_COURSE (PK_ID,STU_ID,COURSE_ID,SCORE,SCHEDULE) values (7,'1709011302','3019586000',null,null);
Insert into SPIDER_MEN.ASS_SELECT_COURSE (PK_ID,STU_ID,COURSE_ID,SCORE,SCHEDULE) values (8,'1609011903','3082040281',null,null);
REM INSERTING into SPIDER_MEN.ASS_STUDENT
SET DEFINE OFF;
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1609011903','张小倩','10002');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1609010002','二娃','10001');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1609010003','三娃','10001');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1609010004','四娃','10001');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1609010005','五娃','10001');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1609010006','六娃','10001');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1609010007','七娃','10001');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1609010008','孙悟空','20001');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1609010009','猪刚鬣','20001');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1609010010','沙悟净','20001');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1709011300','金素贤','10000');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1709011301','郑靓歆','10000');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1709011302','鹏宇','10000');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1709011303','邓婕','10000');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1709011304','宋宗元','10000');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1709011305','徐乾清','20004');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1709011306','丁吕德','10003');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1709011307','朱哲琴','20004');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1709011308','郑雀声','20004');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1709011309','姚子羚','10003');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('20160001  ','张三','10000');
Insert into SPIDER_MEN.ASS_STUDENT (PK_ID,NAME,MAJOR_ID) values ('1609010001','张三','10000');
REM INSERTING into SPIDER_MEN.ASS_TEACHER
SET DEFINE OFF;
Insert into SPIDER_MEN.ASS_TEACHER (PK_ID,NAME) values ('0506010001','刘飞');
Insert into SPIDER_MEN.ASS_TEACHER (PK_ID,NAME) values ('0907180491','宋澳');
Insert into SPIDER_MEN.ASS_TEACHER (PK_ID,NAME) values ('1010010001','李明');
REM INSERTING into SPIDER_MEN.ASS_USER
SET DEFINE OFF;
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1105040001','1234',3,'红灯');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1609011903','$2a$10$A2cxO0Q3DYwGWmxK7MOvyOWvoyvx5zGyLV8VmjkB/EdC9Zw7oTmr.',2,'隔壁老王才是我亲爹');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('0104150015','$2a$10$0fcEPJBFqoj0GscUdwsHXuTKXHiEs6Br/03CwY9F3tgDBwUDNPf1m',3,'Forever_');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('0506010001','$2a$10$F8eIEJUturWWTAcFcxerjuJBuNqCRJ54QZYT4Y4N6gc6bcTEB6RWa',1,'暮冬');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('0907180491','$2a$10$CiB1PqiYPLH2R734IHdgiuMQaGepm.rVf4qmoXS.5tu2maJ1Ddyt.',1,'随风流逝^_^');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1609010002','$2a$10$rDLiIUaRd8W9bnHk.sxP/uZkkHcVXDQq1HhKd0VqOCfD42wrpcdCi',2,'1609010002');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1609010003','$2a$10$dhPsJlcoxdL.p9VPa5Kpqedp7GkAFpOJOGzJjBcAZxSSXG2WmCp4K',2,'1609010003');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1609010004','$2a$10$0FnGL.WgOHd8KRsJzQIyIuvjkMJTS3ZgYeRcSLy.LVg0Rgic4NhF2',2,'1609010004');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1609010005','$2a$10$0RUl7Ab1R4dHFiLaUFPSguEsGCW63GzGnUujJu1xxgY8o72YJMFvu',2,'1609010005');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1609010006','$2a$10$EnklinxZdFUCwqfgJi6wjOZFVnXc.7h/yo4el5eFNck4csKR5xw8a',2,'1609010006');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1609010007','$2a$10$yVlBmWBBUp11a4MKo3R.yebEU/hZ4qZxA33m/757R8utYdZ/o3ijW',2,'1609010007');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1609010008','$2a$10$a34x46zoJ/Grhr9rszHmYedhVsIVKEp0UgA5cSfLy8V5Vr5a/3JGa',2,'1609010008');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1609010009','$2a$10$ZyQop.fJVagLyuMuXp5XB.2PNaKmrNLe89BnQ52KdEoZqbPZ6ctsS',2,'1609010009');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1609010010','$2a$10$pvjXnj9RCMRr88g57WhyQu.3ACwfAWq1dCSzYU2OH/fMYKzcR3TFa',2,'1609010010');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1709011300','$2a$10$7CoPDD67j5ytxtCRKtX69ehZK0X860KrSvqGuJrzikDyyNkQb1HGK',2,'月下、残霞');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1709011301','$2a$10$QrrP9lxnLU7LLnbHnPEtKOynqqYE7jLNnNxlUfZ4Ni0pofG75Ou1O',2,'傻瓜，你是我的一生');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1709011302','$2a$10$pdGG1.GWHBpAPr/Ir9FaGeOm.mrtpwzZKL2yMksgqO4XKJr7XGPOa',2,'久不愈i');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1709011303','$2a$10$IwUEqBD1WVZkY.08EBghWu4x5uqij0KIXAuME0ybTlbMlYxl46nF.',2,'〃 心系一人');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1709011304','$2a$10$PsNjrZCpMoBe/Al9M2y8QOGdfqtZNvYfuog4fqKKzmPafrlrtANSK',2,'烟敛寒林');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1709011305','$2a$10$kY4llgk41QH8g2Xd0IYQxe5fz9RWGcpjlYGUHwZ3AS5Sw.bK4lkl.',2,'归去黄鹤杳');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1709011306','$2a$10$e/FgPsWHHUNidIYo2BI7zua.ak/8VS3rG4XtyT5HcSv/9la.KHoOm',2,'尘埃落定　Somnr▼');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1709011307','$2a$10$CeJ.goIXQyyxRooIC9iiquNkl2acbR.x3LOBqxGGjZm3b4tzAgHuW',2,'─━═蕜伤溡哋嫒ζ');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1709011308','$2a$10$g63afYYo4VKEhLwxm5CMeO/SXitriBktfzeORCJHK8PmlYiV2v2Om',2,'朝飞暮卷');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1709011309','$2a$10$wyjNsu0qaEhRTvZ8vwcavO5/Kbk.ytfxEox/8sh8v7VN6REi/0Qp2',2,'以枪会友ㄣ▄︻┳═一');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('20160001  ','$2a$10$G2kt76QPIVh7teg1LB7VYeXNAwQbVKk4cDJwnbLjIQbNAoQB2hRxy',2,'村头翠花是我的');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1609010001','1234',2,'村头翠花是我的');
Insert into SPIDER_MEN.ASS_USER (PK_ID,PASSWORD,ROLE,NICKNAME) values ('1010010001','1234',1,'画');
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 INDEX_COURSE_MAJORID 正在尝试内部生成器。
CREATE INDEX INDEX_COURSE_MAJORID ON ASS_COURSE (MAJOR_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 INDEX_COURSE_TEACHERID 正在尝试内部生成器。
CREATE INDEX INDEX_COURSE_TEACHERID ON ASS_COURSE (TEACHER_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 INDEX_SELECTCOURSE 正在尝试内部生成器。
CREATE UNIQUE INDEX INDEX_SELECTCOURSE ON ASS_SELECT_COURSE (STU_ID ASC, COURSE_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007663 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007663 ON ASS_USER (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007666 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007666 ON ASS_MAJOR (MAJOR_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007670 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007670 ON ASS_STUDENT (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007675 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007675 ON ASS_TEACHER (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007679 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007679 ON ASS_ADMIN (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007688 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007688 ON ASS_COURSE (COURSE_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007694 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007694 ON ASS_SELECT_COURSE (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007701 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007701 ON ASS_COURSE_TESTPAPER (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007707 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007707 ON ASS_COURSE_EXP (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007722 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007722 ON ASS_BLOG (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007726 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007726 ON ASS_BLOG_LABEL (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007737 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007737 ON ASS_COLLECT_BLOG (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007746 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007746 ON ASS_REPORT_BLOG (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007753 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007753 ON ASS_ATTITUDE_BLOG (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C007770 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C007770 ON ASS_COURSE_UPLOADEXP (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 INDEX DDL。带有 DBMS_METADATA 的 SYS_C009082 正在尝试内部生成器。
CREATE UNIQUE INDEX SYS_C009082 ON ASS_COMMENT_BLOG (PK_ID ASC) 
LOGGING 
TABLESPACE ACADEMIC_RESOURCE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- 无法呈现对象 SPIDER_MEN 的 TRIGGER DDL。带有 DBMS_METADATA 的 DELETE_ASS_BLOG 正在尝试内部生成器。
CREATE TRIGGER DELETE_ASS_BLOG 
BEFORE DELETE 
ON ASS_BLOG
FOR EACH ROW
DECLARE
BEGIN
	DELETE ASS_COMMENT_BLOG WHERE ASS_COMMENT_BLOG.BLOG_ID = :OLD.PK_ID;
	DELETE ASS_ATTITUDE_BLOG WHERE ASS_ATTITUDE_BLOG.BLOG_ID = :OLD.PK_ID;
	DELETE ASS_REPORT_BLOG WHERE ASS_REPORT_BLOG.BLOG_ID = :OLD.PK_ID;
	DELETE ASS_COLLECT_BLOG WHERE ASS_COLLECT_BLOG.BLOG_ID = :OLD.PK_ID;
	DELETE ASS_BLOG_LABEL WHERE ASS_BLOG_LABEL.BLOG_ID = :OLD.PK_ID;
END;
-- 无法呈现对象 SPIDER_MEN 的 TRIGGER DDL。带有 DBMS_METADATA 的 TB_ATTITUDE_BLOG_TRIGGER 正在尝试内部生成器。
CREATE TRIGGER TB_ATTITUDE_BLOG_TRIGGER 
BEFORE INSERT ON ASS_ATTITUDE_BLOG
FOR EACH ROW
BEGIN
	SELECT ASS_ATTITUDE_BLOG_SEQ.NEXTVAL INTO :NEW.PK_ID FROM DUAL;
END;
-- 无法呈现对象 SPIDER_MEN 的 TRIGGER DDL。带有 DBMS_METADATA 的 TB_BLOG_LABEL_TRIGGER 正在尝试内部生成器。
CREATE TRIGGER TB_BLOG_LABEL_TRIGGER 
BEFORE INSERT ON ASS_BLOG_LABEL
FOR EACH ROW
BEGIN
	SELECT ASS_BLOG_LABEL_SEQ.NEXTVAL INTO :NEW.PK_ID FROM DUAL;
END;
-- 无法呈现对象 SPIDER_MEN 的 TRIGGER DDL。带有 DBMS_METADATA 的 TB_BLOG_TRIGGER 正在尝试内部生成器。
CREATE TRIGGER TB_BLOG_TRIGGER 
BEFORE INSERT ON ASS_BLOG
FOR EACH ROW
BEGIN
	SELECT ASS_BLOG_SEQ.NEXTVAL INTO :NEW.PK_ID FROM DUAL;
END;
-- 无法呈现对象 SPIDER_MEN 的 TRIGGER DDL。带有 DBMS_METADATA 的 TB_COLLECT_BLOG_TRIGGER 正在尝试内部生成器。
CREATE TRIGGER TB_COLLECT_BLOG_TRIGGER 
BEFORE INSERT ON ASS_COLLECT_BLOG
FOR EACH ROW
BEGIN
	SELECT ASS_COLLECT_BLOG_SEQ.NEXTVAL INTO :NEW.PK_ID FROM DUAL;
END;
-- 无法呈现对象 SPIDER_MEN 的 TRIGGER DDL。带有 DBMS_METADATA 的 TB_COURSE_EXP_TRIGGER 正在尝试内部生成器。
CREATE TRIGGER TB_COURSE_EXP_TRIGGER 
BEFORE INSERT ON ASS_COURSE_EXP
FOR EACH ROW
BEGIN
	SELECT ASS_COURSE_EXP_SEQ.NEXTVAL INTO :NEW.PK_ID FROM DUAL;
END;
-- 无法呈现对象 SPIDER_MEN 的 TRIGGER DDL。带有 DBMS_METADATA 的 TB_COURSE_TESTPAPER_TRIGGER 正在尝试内部生成器。
CREATE TRIGGER TB_COURSE_TESTPAPER_TRIGGER 
BEFORE INSERT ON ASS_COURSE_TESTPAPER
FOR EACH ROW
BEGIN
	SELECT ASS_COURSE_TESTPAPER_SEQ.NEXTVAL INTO :NEW.PK_ID FROM DUAL;
END;
-- 无法呈现对象 SPIDER_MEN 的 TRIGGER DDL。带有 DBMS_METADATA 的 TB_COURSE_UPLOADEXP_TRIGGER 正在尝试内部生成器。
CREATE TRIGGER TB_COURSE_UPLOADEXP_TRIGGER 
BEFORE INSERT ON ASS_COURSE_UPLOADEXP
FOR EACH ROW
BEGIN
	SELECT ASS_COURSE_UPLOADEXP_SEQ.NEXTVAL INTO :NEW.PK_ID FROM DUAL;
END;
-- 无法呈现对象 SPIDER_MEN 的 TRIGGER DDL。带有 DBMS_METADATA 的 TB_REPORT_BLOG_TRIGGER 正在尝试内部生成器。
CREATE TRIGGER TB_REPORT_BLOG_TRIGGER 
BEFORE INSERT ON ASS_REPORT_BLOG
FOR EACH ROW
BEGIN
	SELECT ASS_REPORT_BLOG_SEQ.NEXTVAL INTO :NEW.PK_ID FROM DUAL;
END;
-- 无法呈现对象 SPIDER_MEN 的 TRIGGER DDL。带有 DBMS_METADATA 的 TB_SELECT_COURSE_TRIGGER 正在尝试内部生成器。
CREATE TRIGGER TB_SELECT_COURSE_TRIGGER 
BEFORE INSERT ON ASS_SELECT_COURSE
FOR EACH ROW
BEGIN
	SELECT ASS_SELECT_COURSE_SEQ.NEXTVAL INTO :NEW.PK_ID FROM DUAL;
END;
-- 无法呈现对象 SPIDER_MEN 的 PROCEDURE DDL。带有 DBMS_METADATA 的 PRO_DELETE_BLOG_USERID 正在尝试内部生成器。
CREATE PROCEDURE PRO_DELETE_BLOG_USERID (
    USER_ID IN ASS_BLOG.USER_ID%TYPE
)AS
BLOG ASS_BLOG%ROWTYPE;
	CURSOR CUR_DELETE_BLOG_USERID IS
		SELECT * FROM ASS_BLOG WHERE ASS_BLOG.USER_ID = USER_ID FOR UPDATE;
BEGIN
	IF CUR_DELETE_BLOG_USERID%ISOPEN = FALSE THEN
		OPEN CUR_DELETE_BLOG_USERID;
	END IF;
		LOOP
			FETCH CUR_DELETE_BLOG_USERID INTO BLOG;
			EXIT WHEN CUR_DELETE_BLOG_USERID%NOTFOUND;
            IF BLOG.USER_ID = USER_ID THEN
                DELETE FROM ASS_BLOG WHERE CURRENT OF CUR_DELETE_BLOG_USERID;
            END IF;
		END LOOP;
	CLOSE CUR_DELETE_BLOG_USERID;
END PRO_DELETE_BLOG_USERID;
-- 无法呈现对象 SPIDER_MEN 的 PROCEDURE DDL。带有 DBMS_METADATA 的 PRO_SELECTBLOGBYID 正在尝试内部生成器。
CREATE PROCEDURE PRO_SELECTBLOGBYID (
	BLOG_ID IN OUT INT,
	BLOG_TITLE OUT varchar2,
	USER_ID OUT CHAR,
	BLOG_CONTENT OUT varchar2,
	FILE_DOWNLOAD OUT varchar2,
	LAUNCH_TIME OUT DATE,
	AUTHORITY OUT SMALLINT,
	NICKNAME OUT varchar2
	)AS
BEGIN
	SELECT B.PK_ID, B.BLOG_TITLE, B.USER_ID, B.BLOG_CONTENT, B.FILE_DOWNLOAD,B.LAUNCH_TIME, B.AUTHORITY, U.NICKNAME
		INTO BLOG_ID, BLOG_TITLE, USER_ID, BLOG_CONTENT, FILE_DOWNLOAD, LAUNCH_TIME, AUTHORITY, NICKNAME
    FROM ASS_BLOG B LEFT JOIN ASS_USER U ON U.PK_ID = B.USER_ID
    WHERE B.AUTHORITY = 2 AND B.PK_ID = BLOG_ID;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO DATA FOUND');
    DBMS_OUTPUT.PUT_LINE(BLOG_TITLE || USER_ID);
END PRO_SELECTBLOGBYID;
-- 无法呈现对象 SPIDER_MEN 的 PROCEDURE DDL。带有 DBMS_METADATA 的 PRO_USER_ANNOUNCE_BLOG 正在尝试内部生成器。
CREATE PROCEDURE PRO_USER_ANNOUNCE_BLOG (
    TMP_USER_ID IN ASS_USER.PK_ID%TYPE,
	TMP_BLOG_TITLE IN ASS_BLOG.BLOG_TITLE%TYPE,
	TMP_BLOG_CONTENT IN ASS_BLOG.BLOG_CONTENT%TYPE,
	TMP_FILE_DOWNLOAD IN ASS_BLOG.FILE_DOWNLOAD%TYPE,
	TMP_LAUNCH_TIME IN VARCHAR2,
	TMP_AUTHORITY IN ASS_BLOG.AUTHORITY%TYPE
)
AS
BEGIN
	INSERT INTO
        ASS_BLOG(BLOG_TITLE,USER_ID,BLOG_CONTENT,FILE_DOWNLOAD,LAUNCH_TIME,AUTHORITY)
		VALUES(TMP_BLOG_TITLE,TMP_USER_ID,TMP_BLOG_CONTENT,TMP_FILE_DOWNLOAD,to_date(to_char(TMP_LAUNCH_TIME,'yyyy-MM-dd hh24:mm:ss'),'yyyy-MM-dd hh24:mm:ss'), TMP_AUTHORITY);
	COMMIT;
END PRO_USER_ANNOUNCE_BLOG;
-- 无法呈现对象 SPIDER_MEN 的 PACKAGE DDL。带有 DBMS_METADATA 的 PACK_DELETE 正在尝试内部生成器。
CREATE 
PACKAGE PACK_DELETE AS
	PROCEDURE PRO_DELETE_COURSE(COURSE_ID ASS_COURSE.COURSE_ID%TYPE);
	PROCEDURE PRO_DELETE_BLOG(BLOG_ID ASS_BLOG.PK_ID%TYPE);
END PACK_DELETE;
-- 无法呈现对象 SPIDER_MEN 的 PACKAGE DDL。带有 DBMS_METADATA 的 PACK_SELECT 正在尝试内部生成器。
CREATE 
PACKAGE PACK_SELECT AS
    TCT T_COURSE_TABLE ;
    TBT T_BLOG_TABLE ;
    TBCT T_BLOGCOMMENT_TABLE;
	FUNCTION FN_LISTCOURSEBYTEACHERID(
			PAGENOW  INT,
			PAGESIZE  INT, 
			TEACHER_ID  char
			) 
			RETURN T_COURSE_TABLE
			;
	FUNCTION FN_LISTCOURSESBYMAJORID(
			PAGENOW  INT,
			PAGESIZE  INT, 
			MAJOR_ID char
			)
			RETURN T_COURSE_TABLE
			;
	FUNCTION FN_LISTAGREEDCOURSES(
			PAGENOW  INT,
			PAGESIZE  INT
			)
			RETURN T_COURSE_TABLE
			;
	FUNCTION FN_LISTALLCOURSES(
			PAGENOW  INT,
			PAGESIZE  INT
			)
			RETURN T_COURSE_TABLE
			;
	FUNCTION FN_LISTBLOGBYUSERNICKNAME(
			PAGENOW  INT,
			PAGESIZE  INT, 
			NICKNAME  char
			)
			RETURN T_BLOG_TABLE
			;
	FUNCTION FN_LISTBLOGBYBLOGTITLE(
			PAGENOW  INT,
			PAGESIZE  INT, 
			BLOGTITLE  char
			)
			RETURN T_BLOG_TABLE
			;
	FUNCTION FN_LISTOWNBLOG(
			PAGENOW  INT,
			PAGESIZE  INT, 
			USERID  char
			)
			RETURN T_BLOG_TABLE
			;
	FUNCTION FN_LISTALLBLOG(
			PAGENOW  INT,
			PAGESIZE  INT
			)
			RETURN T_BLOG_TABLE
			;
    FUNCTION FN_LISTBLOGBYCOURSEID(
            PAGENOW  INT,
			PAGESIZE  INT,
            COURSEID char
            )
            RETURN T_BLOG_TABLE
            ;
    FUNCTION FN_LISTBLOGBYINFO(
            PAGENOW  INT,
			PAGESIZE  INT,
            BLOGINFO char
            )
            RETURN T_BLOG_TABLE
            ;
    FUNCTION FN_LISTBLOGCOMMENTBYID(
            PAGENOW  INT,
			PAGESIZE  INT,
            BLOGID char
            )
            RETURN T_BLOGCOMMENT_TABLE
            ;
END PACK_SELECT;
-- 无法呈现对象 SPIDER_MEN 的 PACKAGE DDL。带有 DBMS_METADATA 的 PACK_USER_DELETE 正在尝试内部生成器。
CREATE 
PACKAGE PACK_USER_DELETE AS
	PROCEDURE PRO_STUDENT_DELETE(USER_ID ASS_USER.PK_ID%TYPE);
	PROCEDURE PRO_TEACHER_DELETE(USER_ID ASS_USER.PK_ID%TYPE);
	PACK_DELETETEACHER_COURSE_ID ASS_COURSE.COURSE_ID%TYPE;
    BLOG_ID ASS_BLOG.PK_ID%TYPE;
END PACK_USER_DELETE;
-- 无法呈现对象 SPIDER_MEN 的 PACKAGE DDL。带有 DBMS_METADATA 的 PACK_USER_RESIGER 正在尝试内部生成器。
CREATE 
PACKAGE PACK_USER_RESIGER AS
	PROCEDURE PRO_USER_ROLE_CASCADE(tmp_pk_id IN ASS_USER.PK_ID%TYPE,
		tmp_pwd IN ASS_USER.PASSWORD%TYPE,
		tmp_role IN ASS_USER.ROLE%TYPE,
		tmp_nickname IN ASS_USER.NICKNAME%TYPE,
		tmp_name IN ASS_STUDENT.NAME%TYPE,
		tmp_major IN ASS_STUDENT.MAJOR_ID%TYPE);
	PROCEDURE PRO_USER_ROLE_CASCADE_ADMIN(tmp_pk_id IN ASS_USER.PK_ID%TYPE ,
		tmp_pwd IN ASS_USER.PASSWORD%TYPE ,
		tmp_role IN ASS_USER.ROLE%TYPE ,
		tmp_nickname IN ASS_USER.NICKNAME%TYPE ,
		tmp_name IN ASS_STUDENT.NAME%TYPE );
	END PACK_USER_RESIGER;
-- 无法呈现对象 SPIDER_MEN 的 PACKAGE BODY DDL。带有 DBMS_METADATA 的 PACK_DELETE 正在尝试内部生成器。
CREATE 
PACKAGE BODY PACK_DELETE AS
	PROCEDURE PRO_DELETE_COURSE(COURSE_ID ASS_COURSE.COURSE_ID%TYPE) AS
	EXP_ID ASS_COURSE_EXP.PK_ID%TYPE;
	BEGIN
		SELECT PK_ID INTO EXP_ID FROM ASS_COURSE_EXP WHERE ASS_COURSE_EXP.PK_ID = COURSE_ID;
		DELETE FROM ASS_COURSE_UPLOADEXP WHERE ASS_COURSE_UPLOADEXP.EXP_ID = EXP_ID;
		DELETE FROM ASS_COURSE_EXP WHERE ASS_COURSE_EXP.COURSE_ID = COURSE_ID;
		DELETE FROM ASS_COURSE_TESTPAPER WHERE ASS_COURSE_TESTPAPER.COURSE_ID = COURSE_ID;
		DELETE FROM ASS_SELECT_COURSE WHERE ASS_SELECT_COURSE.COURSE_ID = COURSE_ID;
		DELETE FROM ASS_COURSE WHERE ASS_COURSE.COURSE_ID = COURSE_ID;
	END PRO_DELETE_COURSE;
	PROCEDURE PRO_DELETE_BLOG(BLOG_ID ASS_BLOG.PK_ID%TYPE) AS
	BEGIN
		DELETE FROM ASS_COMMENT_BLOG WHERE ASS_COMMENT_BLOG.BLOG_ID = BLOG_ID;
		DELETE FROM ASS_ATTITUDE_BLOG WHERE ASS_ATTITUDE_BLOG.BLOG_ID = BLOG_ID;
		DELETE FROM ASS_REPORT_BLOG WHERE ASS_REPORT_BLOG.BLOG_ID = BLOG_ID;
		DELETE FROM ASS_COLLECT_BLOG WHERE ASS_COLLECT_BLOG.BLOG_ID = BLOG_ID;
		DELETE FROM ASS_BLOG_LABEL WHERE ASS_BLOG_LABEL.BLOG_ID = BLOG_ID;
		DELETE FROM ASS_BLOG WHERE ASS_BLOG.PK_ID = BLOG_ID;
	END PRO_DELETE_BLOG;
END PACK_DELETE;
-- 无法呈现对象 SPIDER_MEN 的 PACKAGE BODY DDL。带有 DBMS_METADATA 的 PACK_SELECT 正在尝试内部生成器。
CREATE 
PACKAGE BODY PACK_SELECT AS
	FUNCTION FN_LISTCOURSEBYTEACHERID(
			PAGENOW  INT,
			PAGESIZE  INT, 
			TEACHER_ID  char)
            RETURN T_COURSE_TABLE
	AS
        I NUMBER;
		BEGIN
            I := 1;
            TCT := T_COURSE_TABLE();
			TCT.EXTEND;
            FOR MyRow IN(
                SELECT COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO 
                FROM 
                    (
                        SELECT A.COURSE_ID, A.COURSE_NAME, A.TEACHER_ID, A.MAJOR_ID, A.COURSE_PIC, A.COURSE_OUTLINE_DOWNLOAD, A.HAS_AGREDD, A.COURSE_INFO, ROWNUM RN
                        FROM (SELECT AC.COURSE_ID,AC.COURSE_NAME,AC.TEACHER_ID,AC.MAJOR_ID,AC.COURSE_PIC,AC.COURSE_OUTLINE_DOWNLOAD,AC.HAS_AGREDD,AC.COURSE_INFO 
                        FROM ASS_COURSE AC WHERE AC.TEACHER_ID = TEACHER_ID ) A
                        WHERE ROWNUM  < PAGENOW * PAGESIZE + 1
                    )
                WHERE RN >  (PAGENOW - 1) * PAGESIZE
            )LOOP
                TCT(I) := COURSE_TABLE(MyRow.COURSE_ID, MyRow.COURSE_NAME,MyRow.TEACHER_ID, MyRow.MAJOR_ID,
                                        MyRow.COURSE_PIC, MyRow.COURSE_OUTLINE_DOWNLOAD, MyRow.HAS_AGREDD,
                                        MyRow.COURSE_INFO);
                I := I + 1;
                TCT.EXTEND;
            END LOOP;
            RETURN TCT;
		END FN_LISTCOURSEBYTEACHERID;
    FUNCTION FN_LISTCOURSESBYMAJORID(
			PAGENOW  INT,
			PAGESIZE  INT, 
			MAJOR_ID char
			)
			RETURN T_COURSE_TABLE
	AS	
		I NUMBER;
		BEGIN
            I := 1;
			TCT := T_COURSE_TABLE();
			TCT.EXTEND;
            FOR MyRow IN(
                SELECT COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO 
				FROM
				(
					SELECT  A.COURSE_ID, A.COURSE_NAME, A.TEACHER_ID, A.MAJOR_ID, A.COURSE_PIC, A.COURSE_OUTLINE_DOWNLOAD, A.HAS_AGREDD, A.COURSE_INFO, ROWNUM RN
					FROM (SELECT AC.COURSE_ID,AC.COURSE_NAME,AC.TEACHER_ID,AC.MAJOR_ID,AC.COURSE_PIC,AC.COURSE_OUTLINE_DOWNLOAD,AC.HAS_AGREDD,AC.COURSE_INFO
					FROM ASS_COURSE AC WHERE AC.MAJOR_ID = MAJOR_ID) A
					WHERE ROWNUM  < PAGENOW * PAGESIZE + 1
				)
				WHERE RN >  (PAGENOW - 1) * PAGESIZE
            )LOOP
                TCT(I) := COURSE_TABLE(MyRow.COURSE_ID, MyRow.COURSE_NAME,MyRow.TEACHER_ID, MyRow.MAJOR_ID,
                                        MyRow.COURSE_PIC, MyRow.COURSE_OUTLINE_DOWNLOAD, MyRow.HAS_AGREDD,
                                        MyRow.COURSE_INFO);
                I := I + 1;
                TCT.EXTEND;
            END LOOP;
            RETURN TCT;
		END FN_LISTCOURSESBYMAJORID;
	FUNCTION FN_LISTAGREEDCOURSES(
			PAGENOW  INT,
			PAGESIZE  INT
			)
			RETURN T_COURSE_TABLE
	AS
		I NUMBER;
		BEGIN
            I := 1;
			TCT := T_COURSE_TABLE();
			TCT.EXTEND;
            FOR MyRow IN(
                SELECT COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO  
				FROM
				(
					SELECT A.COURSE_ID, A.COURSE_NAME, A.TEACHER_ID, A.MAJOR_ID, A.COURSE_PIC, A.COURSE_OUTLINE_DOWNLOAD, A.HAS_AGREDD, A.COURSE_INFO, ROWNUM RN
					FROM (SELECT AC.COURSE_ID,AC.COURSE_NAME,AC.TEACHER_ID,AC.MAJOR_ID,AC.COURSE_PIC,AC.COURSE_OUTLINE_DOWNLOAD,AC.HAS_AGREDD,AC.COURSE_INFO FROM ASS_COURSE AC WHERE AC.HAS_AGREDD = 3) A
					WHERE ROWNUM  < PAGENOW * PAGESIZE + 1
				)
				WHERE RN >  (PAGENOW - 1) * PAGESIZE
            )LOOP
                TCT(I) := COURSE_TABLE(MyRow.COURSE_ID, MyRow.COURSE_NAME,MyRow.TEACHER_ID, MyRow.MAJOR_ID,
                                        MyRow.COURSE_PIC, MyRow.COURSE_OUTLINE_DOWNLOAD, MyRow.HAS_AGREDD,
                                        MyRow.COURSE_INFO);
                I := I + 1;
                TCT.EXTEND;
            END LOOP;
            RETURN TCT;
		END FN_LISTAGREEDCOURSES;
	FUNCTION FN_LISTALLCOURSES(
			PAGENOW  INT,
			PAGESIZE  INT
			)
			RETURN T_COURSE_TABLE
	AS
		I NUMBER;
		BEGIN
            I := 1;
			TCT := T_COURSE_TABLE();
			TCT.EXTEND;
            FOR MyRow IN(
                SELECT COURSE_ID,COURSE_NAME,TEACHER_ID,MAJOR_ID,COURSE_PIC,COURSE_OUTLINE_DOWNLOAD,HAS_AGREDD,COURSE_INFO  
				FROM
				(
					SELECT A.COURSE_ID, A.COURSE_NAME, A.TEACHER_ID, A.MAJOR_ID, A.COURSE_PIC, A.COURSE_OUTLINE_DOWNLOAD, A.HAS_AGREDD, A.COURSE_INFO, ROWNUM RN
					FROM (SELECT AC.COURSE_ID,AC.COURSE_NAME,AC.TEACHER_ID,AC.MAJOR_ID,AC.COURSE_PIC,AC.COURSE_OUTLINE_DOWNLOAD,AC.HAS_AGREDD,AC.COURSE_INFO FROM ASS_COURSE AC) A
					WHERE ROWNUM  < PAGENOW * PAGESIZE + 1
				)
				WHERE RN >  (PAGENOW - 1) * PAGESIZE
            )LOOP
                TCT(I) := COURSE_TABLE(MyRow.COURSE_ID, MyRow.COURSE_NAME,MyRow.TEACHER_ID, MyRow.MAJOR_ID,
                                        MyRow.COURSE_PIC, MyRow.COURSE_OUTLINE_DOWNLOAD, MyRow.HAS_AGREDD,
                                        MyRow.COURSE_INFO);
                I := I + 1;
                TCT.EXTEND;
            END LOOP;
            RETURN TCT;
		END FN_LISTALLCOURSES;
	FUNCTION FN_LISTBLOGBYUSERNICKNAME(
			PAGENOW  INT,
			PAGESIZE  INT, 
			NICKNAME  char
			)
			RETURN T_BLOG_TABLE
	AS
		I NUMBER;
		BEGIN
            I := 1;
			TBT := T_BLOG_TABLE();
			TBT.EXTEND;
            FOR MyRow IN(
                SELECT PK_ID, BLOG_TITLE, USER_ID, BLOG_CONTENT, FILE_DOWNLOAD, LT,AUTHORITY,NICKNAME,COURSE_ID
				FROM (
					SELECT B.PK_ID,B.BLOG_TITLE,B.USER_ID, B.BLOG_CONTENT, B.FILE_DOWNLOAD, B.LT, B.AUTHORITY,B.NICKNAME, B.COURSE_ID,ROWNUM RN
					FROM (SELECT B.PK_ID,B.BLOG_TITLE,B.USER_ID, B.BLOG_CONTENT, B.FILE_DOWNLOAD, TO_CHAR(B.LAUNCH_TIME,'yyyy-MM-dd hh24:mi:ss') LT, B.AUTHORITY, U.NICKNAME, B.COURSE_ID
						FROM ASS_BLOG B LEFT JOIN ASS_USER U ON U.PK_ID = B.USER_ID
						WHERE U.NICKNAME LIKE CONCAT(CONCAT('%', NICKNAME),'%') AND B.AUTHORITY = 2) B
					WHERE ROWNUM  < PAGENOW * PAGESIZE + 1
				)
			WHERE RN >  (PAGENOW - 1) * PAGESIZE
            )LOOP
                TBT(I) := BLOG_TABLE(MyRow.PK_ID, MyRow.BLOG_TITLE,MyRow.USER_ID, MyRow.BLOG_CONTENT,MyRow.FILE_DOWNLOAD, MyRow.LT, MyRow.AUTHORITY,MyRow.NICKNAME,MyRow.COURSE_ID);
                I := I + 1;
                TBT.EXTEND;
            END LOOP;
            RETURN TBT;
	END FN_LISTBLOGBYUSERNICKNAME;
	FUNCTION FN_LISTBLOGBYBLOGTITLE(
			PAGENOW  INT,
			PAGESIZE  INT, 
			BLOGTITLE  char
			)
			RETURN T_BLOG_TABLE
	AS
		I NUMBER;
		BEGIN
            I := 1;
			TBT := T_BLOG_TABLE();
			TBT.EXTEND;
            FOR MyRow IN(
                SELECT PK_ID, BLOG_TITLE, USER_ID, BLOG_CONTENT, FILE_DOWNLOAD, LT,AUTHORITY,NICKNAME,COURSE_ID
				FROM (
					SELECT B.PK_ID,B.BLOG_TITLE,B.USER_ID, B.BLOG_CONTENT, B.FILE_DOWNLOAD, B.LT, B.AUTHORITY, B.NICKNAME,B.COURSE_ID,ROWNUM RN
					FROM (SELECT B.PK_ID,B.BLOG_TITLE,B.USER_ID, B.BLOG_CONTENT, B.FILE_DOWNLOAD, TO_CHAR(B.LAUNCH_TIME,'yyyy-MM-dd hh24:mi:ss') LT, B.AUTHORITY, U.NICKNAME,B.COURSE_ID
						FROM ASS_BLOG B LEFT JOIN ASS_USER U ON U.PK_ID = B.USER_ID
						WHERE B.BLOG_TITLE LIKE CONCAT(CONCAT('%', BLOGTITLE),'%') AND B.AUTHORITY = 2) B
					WHERE ROWNUM  < PAGENOW * PAGESIZE + 1
					)
				WHERE RN >  (PAGENOW - 1) * PAGESIZE
            )LOOP
                TBT(I) := BLOG_TABLE(MyRow.PK_ID, MyRow.BLOG_TITLE,MyRow.USER_ID, MyRow.BLOG_CONTENT,MyRow.FILE_DOWNLOAD, MyRow.LT, MyRow.AUTHORITY,MyRow.NICKNAME,MyRow.COURSE_ID);
                I := I + 1;
                TBT.EXTEND;
            END LOOP;
            RETURN TBT;
	END FN_LISTBLOGBYBLOGTITLE;
	FUNCTION FN_LISTOWNBLOG(
			PAGENOW  INT,
			PAGESIZE  INT, 
			USERID  char
			)
			RETURN T_BLOG_TABLE
	AS
		I NUMBER;
		BEGIN
            I := 1;
			TBT := T_BLOG_TABLE();
			TBT.EXTEND;
            FOR MyRow IN(
                SELECT PK_ID, BLOG_TITLE, USER_ID, BLOG_CONTENT, FILE_DOWNLOAD, LT,AUTHORITY, NICKNAME,COURSE_ID
				FROM (
					SELECT B.PK_ID,B.BLOG_TITLE,B.USER_ID, B.BLOG_CONTENT, B.FILE_DOWNLOAD, B.LT, B.AUTHORITY, B.NICKNAME,B.COURSE_ID,ROWNUM RN
					FROM (SELECT B.PK_ID,B.BLOG_TITLE,B.USER_ID, B.BLOG_CONTENT, B.FILE_DOWNLOAD, TO_CHAR(B.LAUNCH_TIME,'yyyy-MM-dd hh24:mi:ss') LT, B.AUTHORITY, U.NICKNAME,B.COURSE_ID
						FROM ASS_BLOG B LEFT JOIN ASS_USER U ON U.PK_ID = B.USER_ID
						WHERE B.USER_ID = USERID) B
					WHERE ROWNUM  < PAGENOW * PAGESIZE + 1
				)
				WHERE RN >  (PAGENOW - 1) * PAGESIZE
            )LOOP
                TBT(I) := BLOG_TABLE(MyRow.PK_ID, MyRow.BLOG_TITLE,MyRow.USER_ID, MyRow.BLOG_CONTENT,MyRow.FILE_DOWNLOAD, MyRow.LT, MyRow.AUTHORITY,MyRow.NICKNAME,MyRow.COURSE_ID);
                I := I + 1;
                TBT.EXTEND;
            END LOOP;
            RETURN TBT;	
	END FN_LISTOWNBLOG;
	FUNCTION FN_LISTALLBLOG(
			PAGENOW  INT,
			PAGESIZE  INT
			)
			RETURN T_BLOG_TABLE
	AS
		I NUMBER;
		BEGIN
            I := 1;
			TBT := T_BLOG_TABLE();
			TBT.EXTEND;
            FOR MyRow IN(
                SELECT PK_ID, BLOG_TITLE, USER_ID, BLOG_CONTENT, FILE_DOWNLOAD, LT,AUTHORITY,NICKNAME,COURSE_ID
				FROM (
					SELECT B.PK_ID,B.BLOG_TITLE,B.USER_ID, B.BLOG_CONTENT, B.FILE_DOWNLOAD, B.LT, B.AUTHORITY, B.NICKNAME,B.COURSE_ID,ROWNUM RN
					FROM (SELECT B.PK_ID,B.BLOG_TITLE,B.USER_ID, B.BLOG_CONTENT, B.FILE_DOWNLOAD, TO_CHAR(B.LAUNCH_TIME,'yyyy-MM-dd hh24:mi:ss') LT, B.AUTHORITY, U.NICKNAME,B.COURSE_ID
						FROM ASS_BLOG B LEFT JOIN ASS_USER U ON U.PK_ID = B.USER_ID
						WHERE B.AUTHORITY = 2) B
					WHERE ROWNUM  < PAGENOW * PAGESIZE + 1
				)
				WHERE RN >  (PAGENOW - 1) * PAGESIZE
            )LOOP
                TBT(I) := BLOG_TABLE(MyRow.PK_ID, MyRow.BLOG_TITLE,MyRow.USER_ID, MyRow.BLOG_CONTENT,MyRow.FILE_DOWNLOAD, MyRow.LT, MyRow.AUTHORITY,MyRow.NICKNAME,MyRow.COURSE_ID);
                I := I + 1;
                TBT.EXTEND;
            END LOOP;
            RETURN TBT;	
	END FN_LISTALLBLOG;
	FUNCTION FN_LISTBLOGBYCOURSEID(
			PAGENOW  INT,
			PAGESIZE  INT,
            COURSEID char
			)
			RETURN T_BLOG_TABLE
	AS
		I NUMBER;
		BEGIN
            I := 1;
			TBT := T_BLOG_TABLE();
			TBT.EXTEND;
            FOR MyRow IN(
                SELECT PK_ID, BLOG_TITLE, USER_ID, BLOG_CONTENT, FILE_DOWNLOAD, LT,AUTHORITY,NICKNAME,COURSE_ID
				FROM (
					SELECT B.PK_ID,B.BLOG_TITLE,B.USER_ID, B.BLOG_CONTENT, B.FILE_DOWNLOAD, B.LT, B.AUTHORITY, B.NICKNAME,COURSE_ID,ROWNUM RN
					FROM (SELECT B.PK_ID,B.BLOG_TITLE,B.USER_ID, B.BLOG_CONTENT, B.FILE_DOWNLOAD, TO_CHAR(B.LAUNCH_TIME,'yyyy-MM-dd hh24:mi:ss') LT, B.AUTHORITY, U.NAME NICKNAME,B.COURSE_ID
						FROM ASS_BLOG B LEFT JOIN ASS_STUDENT U ON U.PK_ID = B.USER_ID
						WHERE B.AUTHORITY = 2 AND B.COURSE_ID = COURSEID) B
					WHERE ROWNUM  < PAGENOW * PAGESIZE + 1
				)
				WHERE RN >  (PAGENOW - 1) * PAGESIZE
            )LOOP
                TBT(I) := BLOG_TABLE(MyRow.PK_ID, MyRow.BLOG_TITLE,MyRow.USER_ID, MyRow.BLOG_CONTENT,MyRow.FILE_DOWNLOAD, MyRow.LT, MyRow.AUTHORITY,MyRow.NICKNAME,MyRow.COURSE_ID);
                I := I + 1;
                TBT.EXTEND;
            END LOOP;
            RETURN TBT;	
	END FN_LISTBLOGBYCOURSEID;
	FUNCTION FN_LISTBLOGBYINFO(
			PAGENOW  INT,
			PAGESIZE  INT,
            BLOGINFO char
			)
			RETURN T_BLOG_TABLE
	AS
		I NUMBER;
		BEGIN
            I := 1;
			TBT := T_BLOG_TABLE();
			TBT.EXTEND;
            FOR MyRow IN(
                SELECT PK_ID, BLOG_TITLE, USER_ID, BLOG_CONTENT, FILE_DOWNLOAD, LT,AUTHORITY,NICKNAME,COURSE_ID
				FROM (
					SELECT B.PK_ID,B.BLOG_TITLE,B.USER_ID, B.BLOG_CONTENT, B.FILE_DOWNLOAD, B.LT, B.AUTHORITY, B.NICKNAME,B.COURSE_ID,ROWNUM RN
					FROM (SELECT B.PK_ID,B.BLOG_TITLE,B.USER_ID, B.BLOG_CONTENT, B.FILE_DOWNLOAD, TO_CHAR(B.LAUNCH_TIME,'yyyy-MM-dd hh24:mi:ss') LT, B.AUTHORITY, U.NICKNAME,B.COURSE_ID
						FROM ASS_BLOG B LEFT JOIN ASS_USER U ON B.AUTHORITY = 2 AND U.PK_ID = B.USER_ID
						WHERE B.BLOG_TITLE = blogInfo OR U.NICKNAME = blogInfo) B
					WHERE ROWNUM  < PAGENOW * PAGESIZE + 1
				)
				WHERE RN >  (PAGENOW - 1) * PAGESIZE
            )LOOP
                TBT(I) := BLOG_TABLE(MyRow.PK_ID, MyRow.BLOG_TITLE,MyRow.USER_ID, MyRow.BLOG_CONTENT,MyRow.FILE_DOWNLOAD, MyRow.LT, MyRow.AUTHORITY,MyRow.NICKNAME,MyRow.COURSE_ID);
                I := I + 1;
                TBT.EXTEND;
            END LOOP;
            RETURN TBT;	
	END FN_LISTBLOGBYINFO;
	FUNCTION FN_LISTBLOGCOMMENTBYID(
			PAGENOW  INT,
			PAGESIZE  INT,
            BLOGID char
			)
			RETURN T_BLOGCOMMENT_TABLE
	AS
		I NUMBER;
		BEGIN
            I := 1;
			TBCT := T_BLOGCOMMENT_TABLE();
            TBCT.EXTEND;
            FOR MyRow IN(
                SELECT PK_ID, BLOG_ID,USER_ID,  COMMENTS, NICKNAME, TIMES
				FROM (
					SELECT CB.PK_ID,CB.BLOG_ID,CB.USER_ID, CB.COMMENTS,CB.TIME TIMES,CB.NICKNAME,ROWNUM RN
					FROM (SELECT CB.PK_ID,CB.BLOG_ID,CB.USER_ID,CB.COMMENTS,TO_CHAR(CB.TIMES,'yyyy-MM-dd hh24:mi:ss') TIME, U.NICKNAME 
						FROM ASS_COMMENT_BLOG CB LEFT JOIN ASS_USER U ON  U.PK_ID = CB.USER_ID
						WHERE CB.BLOG_ID = BLOGID) CB
					WHERE ROWNUM  < PAGENOW * PAGESIZE + 1
					)
				WHERE RN >  (PAGENOW - 1) * PAGESIZE
            )LOOP
                TBCT.EXTEND;
                TBCT(I) := BLOGCOMMENT_TABLE(MyRow.PK_ID, MyRow.BLOG_ID,MyRow.USER_ID, MyRow.COMMENTS,MyRow.NICKNAME, MyRow.TIMES);
                I := I + 1;
            END LOOP;
            RETURN TBCT;	
	END FN_LISTBLOGCOMMENTBYID;
END PACK_SELECT;
-- 无法呈现对象 SPIDER_MEN 的 PACKAGE BODY DDL。带有 DBMS_METADATA 的 PACK_USER_DELETE 正在尝试内部生成器。
CREATE 
PACKAGE BODY PACK_USER_DELETE AS
	PROCEDURE PRO_STUDENT_DELETE(USER_ID ASS_USER.PK_ID%TYPE) AS
	BEGIN
		DELETE FROM ASS_COURSE_UPLOADEXP WHERE STU_ID = USER_ID;
		DELETE FROM ASS_SELECT_COURSE WHERE STU_ID = USER_ID;
		DELETE FROM ASS_COMMENT_BLOG WHERE ASS_COMMENT_BLOG.USER_ID = USER_ID;
		DELETE FROM ASS_REPORT_BLOG WHERE ASS_REPORT_BLOG.USER_ID = USER_ID;
		DELETE FROM ASS_ATTITUDE_BLOG WHERE ASS_ATTITUDE_BLOG.USER_ID = USER_ID;
		DELETE FROM ASS_COLLECT_BLOG WHERE ASS_COLLECT_BLOG.USER_ID = USER_ID;
        SELECT PK_ID INTO BLOG_ID FROM ASS_BLOG WHERE ASS_BLOG.USER_ID = USER_ID;
        DELETE FROM ASS_BLOG_LABEL WHERE ASS_BLOG_LABEL.PK_ID = BLOG_ID;
		DELETE FROM ASS_BLOG WHERE ASS_BLOG.USER_ID = USER_ID;
		DELETE FROM ASS_STUDENT WHERE PK_ID = USER_ID;
		DELETE FROM ASS_USER WHERE PK_ID = USER_ID;
	END PRO_STUDENT_DELETE;
	PROCEDURE PRO_TEACHER_DELETE(USER_ID ASS_USER.PK_ID%TYPE) AS
        CURSOR CUR_COURSE_ID IS
            SELECT COURSE_ID FROM ASS_COURSE WHERE ASS_COURSE.TEACHER_ID = USER_ID;
	BEGIN
		LOOP
			IF NOT CUR_COURSE_ID%ISOPEN THEN
				OPEN CUR_COURSE_ID;
			END IF;
			FETCH CUR_COURSE_ID INTO PACK_DELETETEACHER_COURSE_ID;
			EXIT WHEN CUR_COURSE_ID%NOTFOUND;
			DELETE FROM ASS_COURSE_UPLOADEXP WHERE EXP_ID = (SELECT PK_ID FROM ASS_COURSE_EXP WHERE COURSE_ID = PACK_DELETETEACHER_COURSE_ID);
			DELETE FROM ASS_COURSE_EXP WHERE COURSE_ID = PACK_DELETETEACHER_COURSE_ID;
			DELETE FROM ASS_COURSE_TESTPAPER WHERE COURSE_ID = PACK_DELETETEACHER_COURSE_ID;
			DELETE FROM ASS_SELECT_COURSE WHERE COURSE_ID = PACK_DELETETEACHER_COURSE_ID;
			DELETE FROM ASS_COURSE WHERE COURSE_ID = PACK_DELETETEACHER_COURSE_ID;
		END LOOP;
		CLOSE CUR_COURSE_ID;
		DELETE FROM ASS_COMMENT_BLOG WHERE ASS_COMMENT_BLOG.USER_ID = USER_ID;
		DELETE FROM ASS_REPORT_BLOG WHERE ASS_REPORT_BLOG.USER_ID = USER_ID;
		DELETE FROM ASS_ATTITUDE_BLOG WHERE ASS_ATTITUDE_BLOG.USER_ID = USER_ID;
		DELETE FROM ASS_COLLECT_BLOG WHERE ASS_COLLECT_BLOG.USER_ID = USER_ID;
        SELECT PK_ID INTO BLOG_ID FROM ASS_BLOG WHERE ASS_BLOG.USER_ID = USER_ID;
        DELETE FROM ASS_BLOG_LABEL WHERE ASS_BLOG_LABEL.PK_ID = BLOG_ID;
		DELETE FROM ASS_BLOG WHERE ASS_BLOG.USER_ID = USER_ID;
		DELETE FROM ASS_TEACHER WHERE PK_ID = USER_ID;
		DELETE FROM ASS_USER WHERE PK_ID = USER_ID;
	END PRO_TEACHER_DELETE;
END PACK_USER_DELETE;
-- 无法呈现对象 SPIDER_MEN 的 PACKAGE BODY DDL。带有 DBMS_METADATA 的 PACK_USER_RESIGER 正在尝试内部生成器。
CREATE 
PACKAGE BODY PACK_USER_RESIGER AS
	PROCEDURE PRO_USER_ROLE_CASCADE (
		tmp_pk_id IN ASS_USER.PK_ID%TYPE,
		tmp_pwd IN ASS_USER.PASSWORD%TYPE,
		tmp_role IN ASS_USER.ROLE%TYPE,
		tmp_nickname IN ASS_USER.NICKNAME%TYPE,
		tmp_name IN ASS_STUDENT.NAME%TYPE,
		tmp_major IN ASS_STUDENT.MAJOR_ID%TYPE)	AS
	BEGIN 
		INSERT INTO ASS_USER(PK_ID,PASSWORD,ROLE,NICKNAME)
			VALUES(tmp_pk_id,tmp_pwd,tmp_role,tmp_nickname);
		INSERT INTO ASS_STUDENT(PK_ID,NAME,MAJOR_ID)
			VALUES(tmp_pk_id,tmp_name,tmp_major);
		COMMIT;
	END PRO_USER_ROLE_CASCADE;
	PROCEDURE PRO_USER_ROLE_CASCADE_ADMIN(tmp_pk_id IN ASS_USER.PK_ID%TYPE ,
		tmp_pwd IN ASS_USER.PASSWORD%TYPE ,
		tmp_role IN ASS_USER.ROLE%TYPE ,
		tmp_nickname IN ASS_USER.NICKNAME%TYPE ,
		tmp_name IN ASS_STUDENT.NAME%TYPE ) AS
	BEGIN
		IF tmp_role = 1 THEN	--teacher
		INSERT INTO ASS_USER(PK_ID,PASSWORD,ROLE,NICKNAME)
			VALUES(tmp_pk_id,tmp_pwd,tmp_role,tmp_nickname);
		INSERT INTO ASS_TEACHER(PK_ID,NAME)
			VALUES(tmp_pk_id,tmp_name);
		ELSE 
			INSERT INTO ASS_USER(PK_ID,PASSWORD,ROLE,NICKNAME)
				VALUES(tmp_pk_id,tmp_pwd,tmp_role,tmp_nickname);
			INSERT INTO ASS_ADMIN(PK_ID,NAME)
				VALUES(tmp_pk_id,tmp_name);
		END IF;
		COMMIT;
	END PRO_USER_ROLE_CASCADE_ADMIN;
END PACK_USER_RESIGER;
